algoritmo "ex.2"
// Soma dos quadrados
// Autor : Bianca
// Data : 12/03/2019
// Seção de Declarações 

var

n1:  real
n2:  real
n3:  real
n4:  real
Resultado: real

inicio

// Seção de Comandos
escreval ("Digite um número e em seguida digite outros três")
leia (n1)
leia (n2)
leia (n3)
leia (n4)
Resultado <- (n1^2)+(n2^2)+(n3^2)+(n4^2)
escreval ("Seu cálculo tem como resposta",Resultado)

fimalgoritmo
